#!/usr/bin/env ruby
# frozen_string_literal: true

# Backfill thumbnail generator for album/post/draft images.
#
# Scans assets/images/{posts,albums,drafts}/ for source images (JPEG, PNG,
# WebP, GIF, SVG), generates <basename>-thumb.jpg (<=600w, q78) and
# <basename>-med.jpg (<=1600w, q82) next to each raster source, and writes a
# manifest to _data/image_meta.yml. Animated GIF/WebP get only a thumb of
# their first frame (`animated: true`); SVGs get no variants, only their size.
# The rules are shared with the editor server (scripts/image_pipeline.rb).
#
# Usage:
#   bundle exec ruby scripts/generate_thumbnails.rb [--force] [--only posts|albums|drafts] [--verbose] [--strip-metadata]
#
# Idempotent: skips images whose thumbs already exist and are newer than source.
# --strip-metadata (opt-in) also rewrites existing raster originals that still
# carry EXIF/XMP/IPTC (GPS, camera, capture time) or a rotation tag, the way
# uploads are stored now: orientation baked in, metadata removed, re-encoded
# at quality 92 (animated GIF/WebP: stripped only); their variants are then
# regenerated. Files without metadata are left untouched, so it is safe to
# run twice. It changes committed originals, so review the diff before
# publishing.
# Requires ImageMagick on PATH (brew install imagemagick).

require 'fileutils'
require 'optparse'
require 'yaml'
require 'pathname'
require_relative 'image_pipeline'

abort 'error: mini_magick gem or ImageMagick missing. Run `bundle install` and `brew install imagemagick`.' unless ImagePipeline::MAGICK_AVAILABLE

ROOT      = File.expand_path('..', __dir__)
IMAGE_DIR = File.join(ROOT, 'assets', 'images')
DATA_DIR  = File.join(ROOT, '_data')
MANIFEST  = File.join(DATA_DIR, 'image_meta.yml')

SUBDIRS   = %w[posts albums drafts].freeze

options = { force: false, only: nil, verbose: false, strip: false }
OptionParser.new do |opts|
  opts.banner = 'Usage: generate_thumbnails.rb [options]'
  opts.on('--force', 'Regenerate thumbnails even if up to date') { options[:force] = true }
  opts.on('--only SUBDIR', SUBDIRS, "Only process one of: #{SUBDIRS.join(', ')}") { |v| options[:only] = v }
  opts.on('--verbose', 'Log every processed file') { options[:verbose] = true }
  opts.on('--strip-metadata', 'Rewrite originals that still carry EXIF/XMP/IPTC or a rotation tag') { options[:strip] = true }
  opts.on('-h', '--help', 'Show help') { puts opts; exit }
end.parse!


def format_bytes(n)
  return "#{n} B" if n < 1024
  return format('%.1f KB', n / 1024.0) if n < 1024 * 1024
  format('%.1f MB', n / (1024.0 * 1024.0))
end

def iso_path(abs)
  Pathname.new(abs).relative_path_from(Pathname.new(IMAGE_DIR)).to_s
end

def load_existing_manifest(path)
  return {} unless File.exist?(path)
  data = YAML.safe_load(File.read(path), aliases: false) || {}
  data.is_a?(Hash) ? data : {}
rescue Psych::SyntaxError
  warn "warning: could not parse #{path}; starting fresh"
  {}
end

def sort_hash_deep(obj)
  case obj
  when Hash
    obj.keys.sort.each_with_object({}) { |k, acc| acc[k] = sort_hash_deep(obj[k]) }
  when Array
    obj.map { |x| sort_hash_deep(x) }
  else
    obj
  end
end

def write_manifest_atomically(path, data)
  FileUtils.mkdir_p(File.dirname(path))
  tmp = "#{path}.tmp"
  File.write(tmp, manifest_header + sort_hash_deep(data).to_yaml(line_width: -1))
  File.rename(tmp, path)
end

def manifest_header
  <<~HEADER
    # Generated by scripts/generate_thumbnails.rb. Do not edit by hand.
    # Each key is a path under assets/images/. `cf_id` (when set) is reserved
    # for Cloudflare Images integration and is preserved on regeneration.
  HEADER
end

manifest = load_existing_manifest(MANIFEST)
processed = 0
skipped = 0
errors = 0
stripped = 0

subdirs = options[:only] ? [options[:only]] : SUBDIRS

subdirs.each do |sub|
  src_dir = File.join(IMAGE_DIR, sub)
  next unless Dir.exist?(src_dir)

  Dir.glob(File.join(src_dir, '*')).sort.each do |abs|
    next unless File.file?(abs)
    next unless ImagePipeline::SOURCE_EXTS.include?(File.extname(abs).downcase)
    next if ImagePipeline.variant_file?(abs)

    rel_key = iso_path(abs)
    restripped = false
    if options[:strip] && ImagePipeline.raster?(abs)
      begin
        if ImagePipeline.strip_in_place!(abs)
          restripped = true
          stripped += 1
          puts "strip #{rel_key}"
        end
      rescue StandardError => e
        warn "error stripping #{rel_key}: #{e.message}"
        errors += 1
        next
      end
    end
    if !options[:force] && !restripped && manifest.key?(rel_key) && ImagePipeline.variants_fresh?(abs)
      skipped += 1
      puts "skip  #{rel_key}" if options[:verbose]
      next
    end

    puts "gen   #{rel_key}"

    begin
      fields = ImagePipeline.build_entry(abs, ->(p) { iso_path(p) })
      existing = manifest[rel_key] || {}
      if fields.nil?
        manifest.delete(rel_key) # an SVG with no usable size: nothing to record
        processed += 1
        next
      end
      if options[:verbose]
        %w[thumb med].each do |v|
          puts "  wrote #{fields[v]['src']} (#{fields[v]['w']}x#{fields[v]['h']}, #{format_bytes(File.size(File.join(IMAGE_DIR, fields[v]['src'])))})" if fields[v]
        end
      end
      fields['cf_id'] = existing['cf_id'] if existing.key?('cf_id')
      manifest[rel_key] = fields
      processed += 1
    rescue StandardError => e
      warn "error processing #{rel_key}: #{e.message}"
      errors += 1
    end
  end
end

manifest_keys_on_disk = manifest.keys.select { |k| File.exist?(File.join(IMAGE_DIR, k)) }
removed = manifest.keys - manifest_keys_on_disk
removed.each do |k|
  puts "prune #{k} (source missing)"
  manifest.delete(k)
end

write_manifest_atomically(MANIFEST, manifest)

puts '---'
puts "processed: #{processed}"
puts "skipped:   #{skipped}"
puts "pruned:    #{removed.size}"
puts "stripped:  #{stripped}" if options[:strip]
puts "errors:    #{errors}"
puts "manifest:  #{Pathname.new(MANIFEST).relative_path_from(Pathname.new(ROOT))}  (#{manifest.size} entries)"
exit(errors.zero? ? 0 : 1)
